// Mocks generated by Mockito 5.4.4 from annotations
// in bloc_project_wheather_app/test/domain.usecases/get_trending_movies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc_project_wheather_app/core.errors/server_failer.dart'
    as _i5;
import 'package:bloc_project_wheather_app/data/models/movie_model.dart' as _i6;
import 'package:bloc_project_wheather_app/domain/repositories/movie_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  @override
  _i4.Future<
      _i2.Either<_i5.ServerFailure,
          List<_i6.Result>>> getTrendingMovie() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingMovie,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>.value(
                _FakeEither_0<_i5.ServerFailure, List<_i6.Result>>(
          this,
          Invocation.method(
            #getTrendingMovie,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>.value(
                _FakeEither_0<_i5.ServerFailure, List<_i6.Result>>(
          this,
          Invocation.method(
            #getTrendingMovie,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>);

  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>> searchMovie(
          String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovie,
          [value],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>.value(
                _FakeEither_0<_i5.ServerFailure, List<_i6.Result>>(
          this,
          Invocation.method(
            #searchMovie,
            [value],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>.value(
                _FakeEither_0<_i5.ServerFailure, List<_i6.Result>>(
          this,
          Invocation.method(
            #searchMovie,
            [value],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.ServerFailure,
          List<_i6.Result>>> getPopulatMovie() => (super.noSuchMethod(
        Invocation.method(
          #getPopulatMovie,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>.value(
                _FakeEither_0<_i5.ServerFailure, List<_i6.Result>>(
          this,
          Invocation.method(
            #getPopulatMovie,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>.value(
                _FakeEither_0<_i5.ServerFailure, List<_i6.Result>>(
          this,
          Invocation.method(
            #getPopulatMovie,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.Result>>>);
}
